name: build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  DOTNET_VERSION: '6.0.x'
  

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [linux-x64, linux-arm64]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
          run: dotnet restore

    - name: build
    run: |
    dotnet publish -c Release /p:PublishSingleFile=true /p:PublishTrimmed=true --self-contained -r ${{ matrix.os }} -o "./publish/fastgithub_${{ matrix.os }}" ./FastGithub/FastGithub.csproj
    
    - uses: actions/upload-artifact@v1
      with:
        name: fastgithub_${{ matrix.os }}
        path: ./publish/fastgithub_${{ matrix.os }}/fastgithub
